name: Push documentation
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    if: github.repository == 'asciidoctor/asciidoctor-gradle-plugin'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Combine documentation
        run: |
          cd docs
          ./gradlew --console=plain -q combineDocs
      - name: Publish documentation
        env:
          CI_BRANCH: ${{ github.ref }}
        run: |
          cd docs
          ./gradlew --console=plain --info :gh-pages:publishDocs \
            -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_PUBLISH_USER }} \
            -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_PUBLISH_KEY }} \
            -Dorg.ajoberstar.grgit.auth.force=hardcoded
